* Grimoire World - MMO Sandbox Economy Game with RPG flavors.

#+BEGIN_QUOTE 
 If you don't believe it or don't get it, I don't have the time to try to convince you, sorry. — Satoshi Nakamoto
#+END_QUOTE
#+BEGIN_SRC
                .-~~~~~~~~~-._       _.-~~~~~~~~~-.
            __.'              ~.   .~              `.__
          .'//                  \./                  \\`.
        .'//                     |                     \\`.
      .'// .-~"""""""~~~~-._     |     _,-~~~~"""""""~-. \\`.
    .'//.-"                 `-.  |  .-'                 "-.\\`.
  .'//______.============-..   \ | /   ..-============.______\\`.
.'______________________________\|/______________________________`.
#+END_SRC

** Manifesto

Grimoire demonstrates the *power of CSS* in the browser, a game engine built with pure CSS transformations, React and Clojurescript.

Grimoire demonstrates the *sandbox economy* with real player driven prices powered by Ethereum smart contracts.

Grimoire demonstrates the *holy grail* workflow for online game development: an auto-restartable back-end + a hot-reloadable front-end.

Grimoire demonstrates the *public domain* an open-source game decorated with renaissance paintings.

Grimoire demonstrates the *decentralized* ruleset, real players govern the world, their magic effects the environment, their willpower break walls.

Grimoire demonstrates the *freedom of PKing* with high-traffic PVP areas and a virtuous combat system.

** Start playing:
[[http://grimoire.world]]

Contributing: 
Clone this repo, cd into it and start the development pipeline build.
#+BEGIN_SRC shell
$ git clone git@github.com:aaronpowered/grimoire.git
$ cd grimoire
$ ./dev.sh
#+END_SRC

Your world is started and available at [[http://localhost:3000]].

Start a REPL in an other terminal:
#+BEGIN_SRC shell
$ ./repl.sh
#+END_SRC

The ~auto~ option in the ~system~ boot task takes care of your application lifecycle. Your system will automatically be reset after editing ~handler.clj~. Changes elsewhere that do not require a system restart will be reloaded on the fly everytime you save your work. 

This workflow is built on top of [[http://boot-clj.com/][Boot]], a build tool, and [[https://github.com/danielsz/system/tree/master/examples/boot][system]], a component library. 

Do you feel the creative juices flow? Are you ready for endless hours of sheer creative output?

